### ISSUE TITLE
身份识别错误

### ISSUE THREAD

**Issue by Upcreat** [harry0703/AudioNotes#11]
![image](https://github.com/user-attachments/assets/21b7a2b6-bf04-40f3-8fdf-99deb7324429)
![image](https://github.com/user-attachments/assets/be24ad20-5447-4ef9-93db-e1ef8b078c89)
麻烦问一下，这个是什么原因呢

**Comment by Upcreat** [comment]
已解决

**Comment by harry0703** [comment]
请问你是如何解决的呢？

**Comment by Upcreat** [comment]
感谢您的回复~我是参考了官方文档将这里进行了替换，不知道是不是os.getenv()没有读取到或者读取的内容不正确
![image](https://github.com/user-attachments/assets/eece49c6-b9f6-4404-8178-b7319c8b1e59)
