### ISSUE TITLE
请问如何接入公有云的SaaS模型API

### ISSUE THREAD

**Issue by anthonyshibo** [harry0703/AudioNotes#13]
现在各大模型价格战，API成本很低，如何接入Qwen、DeepSeek、文心等？

**Comment by harry0703** [comment]
建议安装 [One API](https://github.com/songquanpeng/one-api) 作为大模型网关，然后配置 `.env` 文件或者 修改 `docker-compose.yml` 里面的环境变量
```
# ollama配置【把这一部分改成对应one api的配置即可】
OLLAMA_BASE_URL=http://localhost:11434/v1
OLLAMA_MODEL=qwen2:7b
OLLAMA_API_KEY=ollama
```
