### ISSUE TITLE
Translation file for zh-CN not found. Using default translation en-US.

### ISSUE THREAD

**Issue by hexart** [harry0703/AudioNotes#24]
audio notes webui 中的chainlit找不到中文语言文件，请问如何手动翻译并添加？

**Comment by Upcreat** [comment]
+1

**Comment by harry0703** [comment]
这个影响不大，如果要添加的话，可以参考项目下面的这个文件
`.chainlit/translations/en-US.json`
复制为 `zh-CN.json`，然后翻译即可

**Comment by hexart** [comment]
感谢！
