### ISSUE TITLE
文本可识别，但qwen2连不上，总结报错

### ISSUE THREAD

**Issue by hexart** [harry0703/AudioNotes#25]
<img width="766" alt="截屏2024-08-01 15 35 23" src="https://github.com/user-attachments/assets/92a4dfc9-605c-4767-8de1-63ed723bb7cd">
已确认ollama 服务正常，请问从哪里看本地ollama的链接配置？

**Comment by harry0703** [comment]
你需要先在命令行里面执行
```
ollama pull qwen2
```
拉取模型

**Comment by hexart** [comment]
<img width="701" alt="截屏2024-08-01 15 43 34" src="https://github.com/user-attachments/assets/37b1cefa-9ec0-4684-82f9-8f2b5491d866">
http://localhost:11434 返回 Ollama is running

**Comment by hexart** [comment]
> 你需要先在命令行里面执行
> 
> ```
> ollama pull qwen2
> ```
> 
> 拉取模型

已测试，必须使用以下命令重新拉取模型，即使本地已经有了，但名字不一样：
`ollama pull qwen2:7b`
期待作者添加配置界面，可通过菜单选择本地模型。

**Comment by harry0703** [comment]
可以在 `docker-compose.yml` 文件中配置的

```yml
- OLLAMA_BASE_URL=http://host.docker.internal:11434/v1
- OLLAMA_MODEL=qwen2:7b
- OLLAMA_API_KEY=ollama
```
