### ISSUE TITLE
docker compose运行，有以下问题：The requested image's platform (linux/arm64) does not match the detected host platform

### ISSUE THREAD

**Issue by kaikanertan** [harry0703/AudioNotes#3]
docker compose运行，有以下问题：

> webui The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested

**Comment by Upcreat** [comment]
我也遇到了

**Comment by harry0703** [comment]
没有打对应架构（linux/amd64）的镜像，Linux系统里面会报错
你可以使用项目里面的Dockfile，自己编译一个镜像
把代码clone下来，然后执行
```
docker build -t audio-notes .
```

**Comment by GeoZhanglw** [comment]
镜像编译仍然是arm64平台

**Comment by harry0703** [comment]
> 镜像编译仍然是arm64平台

已经重新编译了多平台的镜像了，你重新执行下面的命令即可
```
#一定要重新下载 docker-compose.yml 文件
curl -fsSL https://github.com/harry0703/AudioNotes/raw/main/docker-compose.yml -o docker-compose.yml
docker-compose up
```
