### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by luandro** [harry0703/AudioNotes#8]
When running docker-compose, I get:
`audio_notes_webui  | exec /usr/local/bin/chainlit: exec format error`

**Comment by JzcEmpty** [comment]
same error

**Comment by Jackxwb** [comment]
> When running docker-compose, I get: `audio_notes_webui | exec /usr/local/bin/chainlit: exec format error`

Docker Image `harryliu888/audio-notes:v1.0` only supported linux/arm64

**Comment by zhq1** [comment]
一样的错误

**Comment by harry0703** [comment]
该问题已经修复，更新 `docker-compose.yml` 文件即可
```
curl -fsSL https://github.com/harry0703/AudioNotes/raw/main/docker-compose.yml -o docker-compose.yml
docker-compose up
```
